### ISSUE TITLE
Adding a dish-feature not working

### ISSUE THREAD

**Issue by dichrogfx** [peasypi/FoodPlanner#1]
Traurigerweise findet man nicht das von mir geaddete Dish nicht im JSON-file, sodass ich z.B. keine white sausage hinzufügen konnte

**Comment by peasypi** [comment]
Danke für das konstruktive Feedback, ich werde mich schnellstmöglich um die Lösung des Problems kümmern.

**Comment by peasypi** [comment]
Mit dem neusten Update sollte das Problem behoben sein. MfG
